[package]
name = "unusual_db"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = [
  "macros",
  "net",
  "rt",
  "rt-multi-thread",
  "sync",
] }
log = "0.4.27"
env_logger = "0.11.8"
